# help.py — Comprehensive Help & FAQ for AI Literature Helper

import streamlit as st

st.set_page_config(page_title="ℹ️ Help — AI Literature Helper", page_icon="ℹ️")

# Always visible description
st.title("ℹ️ Help & FAQ — AI Literature Helper")

st.markdown("""
Welcome to **AI Literature Helper** 👋  
This page provides detailed instructions, common issues, and troubleshooting tips.

---

## 🚀 Quick Start
1. Select a mode: **Keyword Search**, **Paste Citation / Text**, or **Lookup by URL / DOI / PDF**.
2. Run the search to fetch papers.
3. Review **AI annotations**: abstract, tags, relevance score.
4. (Optional) Export results to **Zotero**.

---
""")

# Sidebar navigation
section = st.sidebar.radio(
    "📑 Help Topics",
    [
        "Usage Instructions",
        "Boolean Queries",
        "AI Annotations & Relevance",
        "API Errors",
        "Zotero Issues",
        "PDF / URL Problems",
        "Search Results Issues",
        "Paste Citation Mode Issues",
        "Performance & Limits",
        "Tips & Best Practices",
        "FAQs",
        "Ask Gemini",
    ]
)

# Section content
if section == "Usage Instructions":
    st.header("🧭 Usage Instructions")
    st.markdown("""
    - **Keyword Search** → enter topic/keywords, optionally optimize with AI Boolean queries, and select sources.
    - **Paste Citation / Text** → paste Google Scholar results or citations, AI extracts metadata.
    - **URL / DOI / PDF Lookup** → paste a DOI, article URL, or PDF link; metadata is fetched automatically.
    - **Zotero Export** → enable in sidebar, provide credentials, and set relevance threshold.
    """)

elif section == "Boolean Queries":
    st.header("🔤 Boolean Queries")
    st.markdown("""
    - AI can generate Boolean queries with AND/OR/NOT.
    - PubMed truncates queries to 300 characters → keep them concise.
    - Always review/edit AI-suggested queries for precision.
    - Example: `"CRISPR" AND "prime editing" NOT "review"`.
    """)

elif section == "AI Annotations & Relevance":
    st.header("🤖 AI Annotations & Relevance Scoring")
    st.markdown("""
    - **Abstract (AI)**: 10–15 sentences, generated by Gemini.
    - **Tags**:
      - `aRT` → research topic
      - `aTa` → subtopics
      - `aTy` → paper type
      - `aMe` → methods
      - `ai score-N` → relevance score (0–3)
    - **Relevance score (0–3)**:
      - 0 = marginal
      - 1 = low
      - 2 = moderate
      - 3 = highly relevant
    - Use it as a **filter**, not absolute truth.
    """)

elif section == "API Errors":
    st.header("⚠️ API Errors & Fixes")
    st.markdown("""
    **Semantic Scholar**
    - “Semantic Scholar failed” → rate limit exceeded (1 request/sec). Slow down.
    - Missing metadata → Some papers don’t include abstracts/DOIs.

    **PubMed**
    - “ESearch/ESummary failed” → Timeout or network issue. Retry with fewer results.
    - Query too long → PubMed truncates after 300 chars.
    - No abstract returned → Some PubMed entries lack abstracts.

    **Google Fallback**
    - May return irrelevant results. Refine your title search.
    """)

elif section == "Zotero Issues":
    st.header("📥 Zotero Integration Issues")
    st.markdown("""
    - **Initialization error** → Check API key, User ID, and Collection ID.
    - **Skipped export** → Paper scored below threshold or duplicate detected.
    - **Duplicate detection**:
      - Compares Title and DOI.
      - Best-effort only → may miss some.
    - **Allow duplicates** → Toggle in sidebar if needed.
    """)

elif section == "PDF / URL Problems":
    st.header("📄 PDF / URL Problems")
    st.markdown("""
    - **“Not a PDF”**:
      - Some servers mislabel PDFs.
      - Fix → detection also checks `%PDF` file signature.
    - **No text extracted** → Scanned/image-only PDFs cannot be parsed.
    - **Broken URL** → Ensure the link is public and accessible.
    - **Publisher redirects** → May require institutional login. Use NTU proxy links if available.
    """)

elif section == "Search Results Issues":
    st.header("🔎 Search Results Issues")
    st.markdown("""
    - **No results** → Query too specific. Broaden keywords.
    - **Too many irrelevant results** → Use AI Boolean queries, add NOT clauses.
    - **Old papers only** → Add date filters manually in PubMed or Semantic Scholar.
    - **Repeated entries** → Deduplication removes most, but not all duplicates.
    """)

elif section == "Paste Citation Mode Issues":
    st.header("📋 Paste Citation Mode Issues")
    st.markdown("""
    - **“Nothing extracted”** → Format not recognized. Paste one citation per line.
    - **Authors missing/wrong** → AI may confuse affiliations. Verify manually.
    - **Year not detected** → Some citations don’t include years.
    - **Multiple citations merged** → Paste them clearly separated.
    """)

elif section == "Performance & Limits":
    st.header("⚡ Performance & Limits")
    st.markdown("""
    - **Rate limits**:
      - Semantic Scholar → 1 request/second.
      - PubMed → variable, may throttle heavy users.
    - **Timeouts** → Default request timeout is 30–45s.
    - **Progress bar stuck** → Refresh the app.
    - **Large PDF extraction** → Only first 5000–8000 chars are used.
    """)

elif section == "Tips & Best Practices":
    st.header("💡 Tips & Best Practices")
    st.markdown("""
    - Keep keyword queries **short and focused**.
    - Edit Boolean queries before PubMed searches.
    - Paste clean citations (one per line).
    - Start with **smaller result sets** and scale up.
    - Use **priority topics/authors** in the sidebar to influence relevance.
    - Always verify AI abstracts against the original paper.
    """)

elif section == "FAQs":
    st.header("❓ Frequently Asked Questions")
    st.markdown("""
    **Q: Can I trust AI abstracts?**  
    A: They are summaries — always double-check with the original paper.

    **Q: Why does relevance scoring feel wrong sometimes?**  
    A: It’s heuristic, factoring in keywords, venue, and AI judgment. Use as guidance.

    **Q: Can I add my own topics/authors?**  
    A: Yes — in the sidebar preferences. They influence scoring and tags.

    **Q: Does this work for all disciplines?**  
    A: Best for biomedical, computer science, and natural sciences. Some areas may have weaker coverage.

    **Q: Can I export to formats other than Zotero?**  
    A: Not directly. Export via Zotero, then convert to BibTeX, RIS, EndNote, etc.
    """)

elif section == "Ask Gemini":
    st.header("🤖 Ask Gemini")
    st.markdown("""
    Still stuck? You can chat directly with **Google Gemini** for extra help:  
    👉 [**Ask Gemini**](https://gemini.google.com/)
    """)

